on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Ruby
        uses: ruby/setup-ruby@v1
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install stuff
        run: |
          bundle install
          yarn; yarn install
      - name: Run Cypress
        run: bundle exec rake cypress:run
      - name: Run Jest
        run: yarn test
